# Generated by Django 4.1.7 on 2023-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('On Pay Roll', 'On Pay Roll'), ('On Contract Roll', 'On Contract Roll')], default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
