# Generated by Django 4.1.7 on 2023-03-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_userdetailsmodel_education_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='Education_details',
            new_name='education_details',
        ),
    ]
